# Set the working directory to the directory where the script is located
Set-Location -Path $PSScriptRoot

# Acquire variable hashtable from variables.txt
$ExternalVariablesFile = Join-Path $PSScriptRoot "variables.txt"
$ExternalVariables = Get-Content -raw -LiteralPath $ExternalVariablesFile | ConvertFrom-StringData

# Set our in-script variables from contents of variables.txt-hashtable
$MinecraftVersion = $ExternalVariables['MINECRAFT_VERSION']
$ModLoader = $ExternalVariables['MODLOADER']
$ModLoaderVersion = $ExternalVariables['MODLOADER_VERSION']
$JavaArgs = $ExternalVariables['JAVA_ARGS']
$Java = $ExternalVariables['JAVA']

# Clean up quotes from the Java and Java Args variables
$Java = $Java.Trim('"')
$JavaArgs = $JavaArgs.Trim('"')

# Retrieve the server run command and launcher jar location from the files generated by InitializeServer.ps1
$ServerRunCommandFile = Join-Path $PSScriptRoot "server_run_command.txt"
if (!(Test-Path -Path $ServerRunCommandFile -PathType Leaf)) {
    Write-Host "Server run command file not found. Please run InitializeServer.ps1 first."
    PauseScript
    exit 1
}
$ServerRunCommand = Get-Content -raw -LiteralPath $ServerRunCommandFile

$LauncherJarFile = Join-Path $PSScriptRoot "launcher_jar.txt"
if (!(Test-Path -Path $LauncherJarFile -PathType Leaf)) {
    Write-Host "Launcher jar file not found. Please run InitializeServer.ps1 first."
    PauseScript
    exit 1
}
$LauncherJarLocation = Get-Content -raw -LiteralPath $LauncherJarFile

Function Crash {
    Write-Host "Exiting..."
    PauseScript
    exit 1
}

Function global:RunJavaCommand {
    param ($CommandToRun)
    CMD /C "$CommandToRun"
}

Function PauseScript {
    Write-Host "Press any key to continue" -ForegroundColor Yellow
    $host.ui.RawUI.ReadKey("NoEcho,IncludeKeyDown") > $null
}

""
"Starting server..."
"Minecraft version: ${MinecraftVersion}"
"Modloader:         ${ModLoader}"
"Modloader version: ${ModLoaderVersion}"
if (!("${LauncherJarLocation}" -eq "do_not_manually_edit")) {
    "Launcher JAR:      ${LauncherJarLocation}"
}
""
"Java args:         ${JavaArgs}"
"Java path:         ${Java}"
"Run Command:       ${ServerRunCommand}"
"Java version:"
RunJavaCommand "-version"
""

RunJavaCommand "${ServerRunCommand}"

""
"Exiting..."
PauseScript
exit 0
